language: python

python:
  - "3.9"
  - "3.10"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install pytest

# command to run tests, e.g. python setup.py test
script:
    - python setup.py sdist --format=zip
    - pip install dist/whirl*.zip
    - py.test

after_success:
    - pip install coveralls coverage
    - PYTHONPATH=. coverage run --source=whirl -m pytest
    - coverage report
    - coveralls
